### ISSUE TITLE
Add support for file attachments

### ISSUE THREAD

**Issue by panupan** [bitstadium/HockeySDK-Mac#11]
It looks like the API supports file attachments: http://support.hockeyapp.net/kb/api/api-post-custom-crashes

We'd like to use this feature to attach a log file in binary format to the crash report.

**Comment by anlinde** [comment]
Sorry I seem to have forgotten to update this ticket. You can attach binaries to your crash reports, see http://hockeyapp.net/help/sdk/mac/3.2.0/Protocols/BITCrashManagerDelegate.html#//api/name/attachmentForCrashManager:
