### ISSUE TITLE
Use extension-safe only API

### ISSUE THREAD

**Issue by adib** [bitstadium/HockeySDK-Mac#141]
HockeySDK iOS 5.0.0 is [compatible with app extensions](https://github.com/bitstadium/HockeySDK-iOS/issues/454). However HockeySDK-Mac version 5.1.0 is still not marked as safe to use in app extensions.

**Comment by elamalani** [comment]
@adib Thank you for using HockeyApp. This look like a feature request in HockeySDK Mac. Our team is working on [App Center](https://appcenter.ms) which is the next generation of HockeyApp and all the new features are going to be added in [App Center Apple SDK](https://github.com/Microsoft/appcenter-sdk-apple).

**Comment by adib** [comment]
@elamalani This is as simple as toggling two build settings. Change *Require Only App-Extension-Safe API* to *Yes* for both the framework target and the static library target.

Refer to PR #142
