### ISSUE TITLE
HockeySDK insists the keychain be unlocked.

### ISSUE THREAD

**Issue by mr-fixit** [bitstadium/HockeySDK-Mac#146]
During `-[BITHockeyManager startManager]`, the user is prompted to unlock the keychain 2 times.

I would like HockeySDK to not trigger those prompts, yet still to be useful.  I understand that the user won't be able to save or restore the machine's UUID, or the fields in the crash-report dialog.

**Comment by TroubleMakerBen** [comment]
Hey @mr-fixit,

Thx for getting in touch. When are you seeing those prompts?
In release mode, this prompt should appear once when the HockeySDK tries to safe information securely to the keychain. Are you seeing two prompts for an app that's signed for release?
In debug mode, this can happen all the time as your app is not a release but the debug version.

Can you elaborate when the prompts are appearing (release/debug), please?  Which version of macOS and HockeySDK-Mac are you using?

Best,
Benjamin

**Comment by mr-fixit** [comment]
Hi Benjamin.

I'm using HockeySDK-Mac (5.1.0), on macOS 10.13.6.

I was seeing the 2 prompts in my debug build. As you note, my release build only displays the prompt once, and only if the items exist in my keychain.

**Comment by TroubleMakerBen** [comment]
Hey Eric,

Thx for the info and explanation.
I have tagged this issue as a feature request as it's not a bug but an ask for changing a behavior. One of our design goals for the SDK is/was to keep any information user information, e.g. to authenticate or restrict builds safe, so we are using the keychain on the Mac. 
The only solution that I can think of now is to break apart the SDK into different building block and some of them might not use the keychain, which would result in no keychain access warning – depending on what features you'd be using.
Which, brings me to my final point:
At this point, we are hard at work developing, improving the SDKs for [App Center](https://appcenter.ms). One of it's advantages is a fully modular SDK. You can read more about why App Center is the future of HockeyApp and what this means for you on [our website](http://hockeyapp.net/appcenter/about/). There will be releases for the HockeySDK-Mac (and other platforms) but they will be bugfix/maintenance releases.

Don't hesitate to get in touch and thanks for using HockeyApp!

Benjamin
