### ISSUE TITLE
HockeyApp for Mac (the app): Mojave Compatibility

### ISSUE THREAD

**Issue by WayneEld** [bitstadium/HockeySDK-Mac#147]
Is version 5.1.0 compatible with macOS Mojave? I am currently getting this from the HockeyApp integration application: "The wizard is not compatible with this setup to check if the SDK was integrated successfully."

**Comment by ElektrojungeMS** [comment]
Hey @WayneEld,

Apologies about the issues. We are currently working on compatibility with macOS Mojave.

As a workaround, can you try integrating the SDK by [dragging & dropping the SDK's binary directly](https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-macos#2-setup)?

**Comment by ElektrojungeAtWork** [comment]
Hey @WayneEld,

we just released HockeyApp for Mac 2.0.22 that fixes this issue. It is available at https://hockeyapp.net/releases/mac/.

Thanks for your patience and for using HockeyApp!

Benjamin
