### ISSUE TITLE
HockeySDK-Mac 5.11 not reporting crashes in Photo App Extension. 5.10 worked ok

### ISSUE THREAD

**Issue by markltownsend** [bitstadium/HockeySDK-Mac#153]
I upgraded to the 5.11 HockeySDK-Mac hoping it might fix the keychain pop up issue, but it didn't. Instead, it no longer reports crashes in my case which is in a Photos App Extension.  v5.10 worked fine.  I'll be downgrading it in my project.

**Comment by bmourat** [comment]
Hi @markltownsend 
I've tried reproducing this issue with `Today Extensions` and it works fine. Could you please provide some info on what photo extension are you using and how do you initialize HockeySDK in it?

**Comment by markltownsend** [comment]
Hi @bmourat, I am developing a Photos Project Extension in 10.13+.  I recently just added HockeySDK 5.10 to the app to the AppStore version.  This reported crashes without issue.  However, after updating to 5.11, crash reports stopped coming in.  The only other change was that I had to manually update the dSYM files into the Hockey instance for the AppStore which created the version for it rather than have our Jenkins process upload the dSYMs to create the version.

I am using the following code snippet to start HockeySDK in the main view controller of the extension
`if !PhotoProjectViewController.didSetupHockeySDK {
        BITHockeyManager.shared().configure(withIdentifier: hockeyAppId)
        BITHockeyManager.shared().isCrashManagerDisabled = false
        BITHockeyManager.shared().crashManager.isAutoSubmitCrashReport = true
        BITHockeyManager.shared().isMetricsManagerDisabled = false
        BITHockeyManager.shared().logLevel = .error
        BITHockeyManager.shared().start()
        PhotoProjectViewController.didSetupHockeySDK = true
    }`

I believe that the only thing that might have changed is the logLevel went from .debug to .error.

**Comment by bmourat** [comment]
Hi @markltownsend 
I've tried Photos Project Extension and didn't notice any difference. Crash reporting seems to be working in version 5.1.1. Here is my [sample app](https://github.com/bmourat/HockeySDKMacOSPhotoExt), maybe I'm doing something wrong?

**Comment by ElektrojungeAtWork** [comment]
Hey @markltownsend,
We haven't heard from you in a while and are wondering if you can help us with reproducing the issue? In case you would be able to share a sample or maybe even your code, please get in touch through https://support.hockeyapp.net and you'll be able to share more code under an NDA there.
Thanks for your time and help!

**Comment by ElektrojungeAtWork** [comment]
Hey Mark,

we haven't heard from you in a while so I'm closing this issue. Please don't hesitate to get in touch and reopen this issue again if you run into the issue again or you have some time on your hands.

Best,
Benjamin
