### ISSUE TITLE
Change INSTALL_PATH

### ISSUE THREAD

**Issue by mledford** [bitstadium/HockeySDK-Mac#23]
I would like to see INSTALL_PATH be changed to @rpath/Frameworks. LD_RUNPATH_SEARCH_PATHS can then be specified allowing more flexibility with where the framework is placed.

**Comment by anlinde** [comment]
We just released version 3.2.0 of the SDK which now uses `@rpath`. See http://hockeyapp.net/blog/2015/09/21/hockeysdk-mac-3-2-0-release-notes.html
