### ISSUE TITLE
Add -[BITCrashManager setCrashCallbacks:]

### ISSUE THREAD

**Issue by iccir** [bitstadium/HockeySDK-Mac#25]
Currently, the iOS version of the HockeySDK has -[BITCrashManager setCrashCallbacks:], which calls setCrashCallbacks: on the underlaying `BITPLCrashReporter`.  I need this functionality in the OS X version of HockeySDK too.

**Comment by anlinde** [comment]
Closing this ticket, since this feature is already available in version 3.0. See the commit here: 45c97b1dc204820f877ce0dfcf06f2be8520c9bc
