### ISSUE TITLE
No such module 'HockeySDK'

### ISSUE THREAD

**Issue by iluuu1994** [bitstadium/HockeySDK-Mac#31]
I'm trying to import the HockeySDK using Swift:

```
import HockeySDK
```

I've added the _HockeySDK-Mac_ project to my workspace, I've added it to _Linked Frameworks and Libraries_ and also _Link Binary with Libraries_. Nonetheless, when I try to import it I get the error:

> No such module 'HockeySDK'

I've linked a thousand frameworks like this. Any clue what's wrong?

**Comment by borisyurkevich** [comment]
As from Version 3.5.7 bridging header no longer required.

**Comment by parthmakadiya12** [comment]
I also Faced the same issue .

Then I delete their Framework folder and Create a New Framework Group
Then I follow the general steps of Hockey Mac Application .
At the drag and drop I just unchecked copy and create group.
And then import Hockey app ..

And Build Successful.

**Comment by TroubleMakerBen** [comment]
@parthmakadiya12 I'm glad it worked out for you. If you're running into issues in the future, please don't hesitate to get in touch via [Support](https://support.hockeyapp.net).

**Comment by Sundy0828** [comment]
I have the same problem.  I tried to delete the framework folder and create a new one, then follow rest of the directions, but that didn't work.  And on the newer version it says bridging header is no longer needed.

**Comment by Sundy0828** [comment]
@TroubleMakerBen ,

I got it to run by adding the other frameworks listed in advanced setup in addition to the hockeyapp framework on https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/hockeyapp-for-ios 

I actually have a new problem, after i finished the process it shows my app on hockey app, but i can't download it on my phone.  It says that i basically have to wait for an .ipa file i think.  Is there any way to get that without be a developer?

**Comment by TroubleMakerBen** [comment]
@Sundy0828 I'm glad that you were able to figure this out.

About your other question: You need to have a (paid) developer with Apple to sign applications and distribute those. This is a limitation by Apple and has nothing to do with HockeyApp, which does not provide code signing for you.

(Just another FYI: `.ipa` files are for iOS apps, and `.app` files are macOS apps.)
