### ISSUE TITLE
Expire OS X Beta version

### ISSUE THREAD

**Issue by iluuu1994** [bitstadium/HockeySDK-Mac#32]
Is there a way to manually expire a version so beta users can't open it anymore? In the documentation I found out that this is possible by revoking a certificate on iOS but that this doesn't work on OS X. 

I've seen this done before, e.g. by Dash. Maybe they implemented that functionality themselves, but that would be a handy feature.

**Comment by anlinde** [comment]
Hi guys, sorry for the delay.

We don't have any plans to add such a feature to the HockeySDK at the moment.

Sorry.
