### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by aquarius** [bitstadium/HockeySDK-Mac#46]
I'm getting a `Headers/BITCrashManager.h:178:5: Declaration is marked with '\deprecated' command but does not have a deprecation attribute` warning when I add HockeySDK-Mac to my project.

The issue appears to be that in the declaration of the disableMachExceptionHandler property, ` __attribute__((deprecated("")))`is missing.

Copying the declaration from `enableMachExceptionHandler` should be the correct solution.

**Comment by eelco** [comment]
This was fixed in https://github.com/bitstadium/HockeySDK-Mac/commit/541b11ba04c2f26a8a6e4638d1dc281e13cad42a

I’m wondering when this will be released though, we’re using the HockeySDK-Mac Cocoapod and this is currently the only warning in our project 😕

**Comment by anlinde** [comment]
We just released version 3.2.0 of our SDK with this fix included. See http://hockeyapp.net/blog/2015/09/21/hockeysdk-mac-3-2-0-release-notes.html
