### ISSUE TITLE
BITCrashMetaData.h missing from HockeySDK.h

### ISSUE THREAD

**Issue by clausjoergensen** [bitstadium/HockeySDK-Mac#49]
BITCrashMetaData.h is not included in the HockeySDK.h, preventing usage of the BITCrashManager.handleUserInput method without explicitly including it.

**Comment by anlinde** [comment]
This has been fixed here: https://github.com/bitstadium/HockeySDK-Mac/commit/963afbde874e8982f4a3219c6c2e805d3987fcdb
