### ISSUE TITLE
Add a C/C++ API

### ISSUE THREAD

**Issue by MartinDelille** [bitstadium/HockeySDK-Mac#57]
This would be nice to have a C/C++ API for project using Qt for example.

**Comment by anlinde** [comment]
Hi Martin,

thanks for your feedback. We don't have something like that on our table at the moment. If anyone wants to write a wrapper for C/C++ it would be great.

Best,
Andreas

**Comment by TroubleMakerBen** [comment]
We won't have any capacity to work on this right now, so we're closing this issue for now.

Best,
Benjamin

**Comment by MartinDelille** [comment]
No problem. Objective-C bridging works by the way so it is not mandatory.
