### ISSUE TITLE
How to migrate telemetry events from Application Insights to HockeySDK

### ISSUE THREAD

**Issue by ChristianPraherKoeppl** [bitstadium/HockeySDK-Mac#58]
Hello everyone,

since MS Application Insights (https://github.com/Microsoft/ApplicationInsights-OSX) is deprecated:
I'm only interested in sending custom telemetry data to the Azure backend. Do we need to shift to HockeySDK eventually? If so, can I turn off all features of Hockey except custom telemetry (no crash reports, no feedback, no software upgrade stuff, ...)?

How would I go about migrating code from App Insights to HockeySDK?
From quickly looking at the code of the HockeySDK I do not see a direct correspondence for sending telemetry events to the Microsoft Azure cloud.
 
So, could you please show me how to translate the following App Insights code snippet to HockeySDK:
`[MSAIApplicationInsights setupWithInstrumentationKey:key];`
`[[MSAIApplicationInsights sharedInstance] setDebugLogEnabled:YES];`
`[[MSAIApplicationInsights sharedInstance] setUserWithConfigurationBlock:^(MSAIUser *user) { `
`        user.accountAcquisitionDate = @"MyAcquisitionDate"; `
`        user.accountId = @"MyAccountID"; `
`        user.userId = @"MyUserID"; `
`        user.userAgent = @"MyUserAgent"; `
` }]; `
` [MSAIApplicationInsights start]; `

`[MSAITelemetryManager trackEventWithName:@"MyEventName" properties:myPropertiesDict measurements:myMetricsDict]; `

Thanks!

Christian

**Comment by lumaxis** [comment]
Hey Christian!

Custom Events are not yet available on HockeyApp but we are working on this right now. If you want to get access to it as soon as it's available, I recommend having a look at http://hockeyapp.net/preseason/
In the meantime, Application Insights will still be around, it will just not see any further development.

**Comment by lumaxis** [comment]
We published more information on the transition from Application Insights to HockeyApp here: https://azure.microsoft.com/en-us/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/
