### ISSUE TITLE
Add possibility to add feedback attachments programmatically

### ISSUE THREAD

**Issue by tonklon** [bitstadium/HockeySDK-Mac#59]
It would be great if one could add attachments to da feedback message programmatically. This could be used for log files, screenshots, etc. in case the feedback is used to create a bug report.

**Comment by lumaxis** [comment]
Yep! We've been wanting to do this for a long time :+1:

**Comment by skosyi** [comment]
We all want it... please...

**Comment by TroubleMakerBen** [comment]
@skosyi I know. We're just swamped with work right now, so I can't really give an ETA on this. -.-

**Comment by TroubleMakerBen** [comment]
Hey guys,
we won't have this coming up any time in the next months, closing the issue to reflect the state of this better.

Best,
Benjamin
