### ISSUE TITLE
Memory leak in [BITSender sendUsingURLSessionWithRequest:filePath:]

### ISSUE THREAD

**Issue by blach** [bitstadium/HockeySDK-Mac#70]
You are creating a new `NSURLSession` each time you send telemetry. This causes memory leaks each time. (discovered with Instruments)

I guess this happens because you are not keeping a reference to the session and you are not calling `[NSURLSession finishTasksAndInvalidate]`. You probably should not create a new NSURLSession each time. Using `[NSURLSession sharedSession]` seems to be ideal for this.

I could fix the leaks by replacing the following lines in `[BITSender sendUsingURLSessionWithRequest:filePath:]`:

replace

```objc
  NSURLSessionConfiguration *sessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
  NSURLSession *session = [NSURLSession sessionWithConfiguration:sessionConfiguration];
```
with 

```objc
  NSURLSession *session = [NSURLSession sharedSession];
```

**Comment by lumaxis** [comment]
Hi @blach!
This is already fixed in the current `develop` branch and also the `4.1.0-beta.x` versions we have in prerelease right now. We now use a local property for the session and lazy load it, see here: https://github.com/bitstadium/HockeySDK-Mac/blob/939f02a0912f68f970c6b59bc0459ec9930813b4/Classes/Telemetry/BITSender.m#L185-L191

**Comment by thebugcode** [comment]
This is also an issue for HockeySDK for iOS. Is it solved there as well?

**Comment by lumaxis** [comment]
Yes, this is solved in the current [`develop` branch](https://github.com/bitstadium/HockeySDK-iOS/blob/c25fd45f5e7ca4a03637691aba27ba8b410e09a9/Classes/BITSender.m#L188-L194) and also the current 4.1.0-beta version.

**Comment by thebugcode** [comment]
Thanks Lukas :)
